# Generated by Django 3.0.6 on 2020-06-03 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_searched', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(default='default.jpg', upload_to='images')),
                ('title', models.CharField(default='None', max_length=255)),
                ('duration', models.CharField(default='None', max_length=255)),
                ('creator', models.CharField(default='None', max_length=255)),
                ('link', models.CharField(default='None', max_length=255)),
                ('description', models.CharField(default='None', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_picture', models.ImageField(default='default.jpg', upload_to='images')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='McViewer.Search')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='first_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='McViewer.Video'),
        ),
    ]
