# Generated by Django 3.0.5 on 2020-06-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('McViewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default='None', max_length=255)),
                ('user', models.ManyToManyField(blank=True, to='McViewer.UserProfile')),
            ],
        ),
    ]
