# Generated by Django 3.0.6 on 2020-06-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('McViewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='video_id',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
