# Generated by Django 3.0.5 on 2020-06-01 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('McViewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_searched', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='video',
            name='creator',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='video_thumbnails'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_picture', models.ImageField(blank=True, upload_to='profile_image')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='McViewer.Search')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='first_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='McViewer.Video'),
        ),
    ]
