# Generated by Django 3.0.6 on 2020-06-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('McViewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(default='images/logo.jpg', upload_to='images'),
        ),
    ]
