# Generated by Django 3.0.5 on 2020-06-07 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('McViewer', '0002_privatenetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenetwork',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='privatenetwork',
            name='title',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
