# Generated by Django 3.0.6 on 2020-06-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('McViewer', '0002_auto_20200601_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='McViewer.Search'),
        ),
    ]
